config/routes.rb
Rails.application.routes.draw do


  namespace :app do
    namespace :projects do
      get 'compilations/show'
    end
  end

  devise_for :users,
             controllers: {
               sessions:      'auth/users/sessions',
               registrations: 'auth/users/registrations',
               # passwords:     'auth/users/passwords'
             }

  as :user do
    get '/login', to: 'auth/users/sessions#new'
  end

  scope module: 'app' do
    resources :tags, only: [:index]

    resources :resourceships  do
      # for resourceship's notes field/attribute
      resource :note, only: [:edit, :update], controller: 'resourceships/notes'
      resource :favourite, only: [:update], controller: 'resourceships/favourites'
    end

    resources :themes, only: [:index, :new, :create, :edit, :update, :destroy] do
      # :new, :create => themes without projects,
      # added :edit, :update after habtm

      # for theme's notes => stored in project_theme_assigment model
      resource :note, only: [:show, :edit, :update], controller: 'themes/notes'

      resources :sub_notes, controller: 'themes/sub_notes' # v2 format

      # for compilation of all notes in theme
      resource :note_compilation, only: [:show], controller: 'themes/compilations'

      # for autocompleting theme title
      get :autocomplete_theme_title, on: :collection
    end
    get '/themes/tid/:tid', to: 'themes#index', as: :themes_tid

    resources :resources do
      resource :citation, only: [:show]
      resource :note, only: [:show, :edit, :update], controller: 'resources/notes'
    end
    get '/resources/c/:code', to: 'resources#index', as: :resources_code
    get '/resources/i/:ids', to: 'resources#index', as: :resources_ids

    resources :projects do
      resources :themes, only: [:new, :create, :edit, :update] do
        # :new, :create => themes from projects
        resources :resourceships
      end
      # for compilation of all notes in all themes
      resource :note_compilation, only: [:show], controller: 'projects/compilations'
    end
    get 'projects/:id/tid/:tid', to: 'projects#show', as: :project_themes_tid

    resource :profile, only: [:show]

    namespace :help do
      resources :messages, only: [:new, :create]
    end

    # root to: 'projects#index'
  end

  get '/alpha', to: 'site/pages#alpha'
  get '/terms', to: 'site/pages#terms'
  get '/privacy', to: 'site/pages#privacy'
  get '/robots.txt', to: 'site/pages#robots'
  get '/welcome', to: 'site/pages#welcome'

  # root to: 'site/pages#welcome'
  root to: 'site/pages#mvp'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :account

  validates :name, :email, :body, presence: true
end

app/controllers/app/help/messages_controller.rb
class App::Help::MessagesController < App::BaseController
  layout false


  def new
    @message = current_account.messages.new
  end


  def create
    @message = current_account.messages.new(message_params)
    if @message.save
      flash[:success] = "Thanks for your message. We will get back to you asap :)"
    else
      flash[:error] = "Failed to send your message. Please check that "\
                      "all fields are completed. Thanks :)"
    end
    redirect_to request.referer
  end


  private
  def message_params
    params.require(:message).permit(
      :name,
      :email,
      :body
    )
  end
end

app/helpers/app/help/messages_helper.rb
module App::Help::MessagesHelper
end

app/views/app/help/messages/new.html.erb
<%= render partial: 'app/modal_dialog_header',
           locals:  {
               title:     "Drop us a line!",
               sub_title: nil
           }
%>

<%= form_for @message, url: help_messages_path, html:{id: 'form'}  do |f| %>

  <div class="modal-body">
    <div class="row">
      <div class="col d-flex justify-content-center">

        <p class="justify-content-center">
          Having problems? Any questions or suggestions? Let us know!
          <br>
          We're very happy to help you get the most out of ResourceNote :)
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-6 form-group">
        <%= f.text_field :name, class: "form-control form-isti position-static",
                         placeholder:  "Name" %>
      </div>
      <div class="col-6 form-group">
        <%= f.email_field :email,
                          class:       "form-control form-isti position-static",
                          placeholder: "Email" %>
      </div>
      <div class="col-12 form-group">
        <%= f.text_area :body, class: "form-control form-isti position-static",
                        placeholder:  "Message" %>
      </div>
    </div>
  </div> <!--end modal-body-->

  <%= render partial: 'app/modal_dialog_footer',
             locals:  {
                 f:     f,
                 save:  "Send",
                 close: "Close"
             }
  %>
<% end %>